title: MicroProfile Extensions
author: Phillip Kruger
email: phillip.kruger@gmail.com
description: Some extensions for MicroProfile

# twitter_username: phillipkruger
# github_username:  phillipkruger

sass:
    style: compressed