# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: MicroProfile Extensions
description: "A collection of community extension for Eclipse MicroProfile"
keywords: "MicroProfile"
url: https://www.microprofile-ext.org/
baseurl: ""
thumb: /images/microprofile-ext-logo.png

google_analytics: UA-106577215-3
repo: https://github.com/microprofile-extensions

# Author settings
author:
  email: microprofile.ext@phillip-kruger.com
  url: https://www.microprofile-ext.org/
  github: https://github.com/microprofile-extensions
  twitter: https://twitter.com/MicroprofileE
#  facebook: https://facebook.com/umdevux
#  linkedin: https://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: about
    title: About
 # - slug: icons
 #   title: Icons
 # - slug: blog
 #   title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
